site_name: AI-SERVIS Documentation
site_description: Modular Car AI Server — Android-first with ESP32 and optional Pi gateway
repo_url: https://github.com/sparesparrow/ai-servis
repo_name: sparesparrow/ai-servis
theme:
  name: mkdocs
nav:
  - Overview: index.md
  - Architecture:
    - System Overview: architecture/overview.md
    - Diagrams: architecture/diagrams.md
  - Install:
    - Phone Edition: install/phone.md
    - Hybrid Edition: install/hybrid.md
    - Pro Edition: install/pro.md
    - Pi Gateway (Standalone): install/pi-gateway.md
    - Dev (No Pi): install/dev-docker.md
    - Installer Checklist: install/installer-checklist.md
  - Wiring & Power: wiring.md
  - API & Contracts:
    - Overview: api/overview.md
    - Changelog: api/changelog.md
  - Privacy:
    - DPIA Template: privacy/dpia-template.md
  - Troubleshooting: troubleshooting.md
plugins:
  - search
  - mermaid2
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.superfences

# --- Auto-appended by apply-exported-assets.sh ---
# If nav is managed manually, ensure these entries are present:
# - Universal:
#   - Proposal: docs/ai-servis-universal-proposal.md
#   - Implementation Ready: docs/implementation-ready-summary.md
#   - Architecture Diagrams: docs/architecture/diagrams.md
#   - Master TODO: docs/TODO-master-list.md
