name: Android Build

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'android/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'android/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew

    - name: Build with Gradle
      run: |
        cd android
        ./gradlew assembleDebug
        VERSION_CODE=${{ github.run_number }} VERSION_NAME=${{ github.ref_name }} ./gradlew clean bundleRelease assembleRelease

    - name: Run tests
      run: |
        cd android
        ./gradlew test
        ./gradlew connectedAndroidTest

    - name: Upload debug APK
      uses: actions/upload-artifact@v3
      with:
        name: ai-servis-app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk

    - name: Sign release artifacts
      if: github.ref == 'refs/heads/main'
      env:
        KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      run: |
        mkdir -p android/keystore
        echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/keystore/release.keystore
        echo "storeFile=android/keystore/release.keystore" > keystore.properties
        echo "storePassword=${STORE_PASSWORD}" >> keystore.properties
        echo "keyAlias=${KEY_ALIAS}" >> keystore.properties
        echo "keyPassword=${KEY_PASSWORD}" >> keystore.properties
        cd android
        VERSION_CODE=${{ github.run_number }} VERSION_NAME=${{ github.ref_name }} ./gradlew --no-daemon bundleRelease assembleRelease

    - name: Upload AAB artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: ai-servis-app-release
        path: |
          android/app/build/outputs/bundle/release/app-release.aab
          android/app/build/outputs/apk/release/app-release.apk

    - name: Upload to Play Console (Internal)
      if: github.ref == 'refs/heads/main'
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        packageName: cz.aiservis.app
        releaseFiles: android/app/build/outputs/bundle/release/app-release.aab
        track: internal
