name: Android Build

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'android/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'android/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew

    - name: Build with Gradle
      run: |
        cd android
        ./gradlew assembleDebug
        ./gradlew assembleRelease

    - name: Run tests
      run: |
        cd android
        ./gradlew test
        ./gradlew connectedAndroidTest

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: ai-servis-app
        path: android/app/build/outputs/apk/debug/app-debug.apk

    - name: Upload to Play Console (Internal)
      if: github.ref == 'refs/heads/main'
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        packageName: cz.aiservis.app
        releaseFiles: android/app/build/outputs/apk/release/app-release.apk
        track: internal
